name: matomo

on:
  push:
    tags:
      - 'matomo-[0-9]+.[0-9]+.[0-9]+'

jobs:
  matomo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: matomo

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: docker/setup-qemu-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: tag
        id: tag
        run: |
          VERSION=$(echo "${{github.ref_name}}" | cut -d "-" -f 2)
          echo "version:" $VERSION
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v4
        with:
          context: matomo
          push: true
          tags: glasskube/matomo:latest, glasskube/matomo:${{ steps.tag.outputs.VERSION }}
